Document: wlt-script-0.1
Title: Debian wlt-script-0.1 Manual
Author: <insert document author here>
Abstract: This manual describes what wlt-script-0.1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wlt-script-0.1/wlt-script-0.1.sgml.gz

Format: postscript
Files: /usr/share/doc/wlt-script-0.1/wlt-script-0.1.ps.gz

Format: text
Files: /usr/share/doc/wlt-script-0.1/wlt-script-0.1.text.gz

Format: HTML
Index: /usr/share/doc/wlt-script-0.1/html/index.html
Files: /usr/share/doc/wlt-script-0.1/html/*.html
