.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WLT" "1" "June 2015" "USTC Linux User Group" "User Commands"
.\" Workaround added for Chinese display.
.\" by manpages-zh project
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~
.\" workaround: for puctuations and line-breaking
.\" copied from groff Japanese l10n file
.ds locale chinese
.class [CJKprepunct] \
  , : ; > } \
  \[u3001] \[u3002] \[uFF0C] \[uFF0E] \[u30FB] \[uFF1A] \[uFF1B] \[uFF1F] \
  \[uFF01] \[uFF09] \[u3015] \[uFF3D] \[uFF5D] \[u300D] \[u300F] \[u3011] \
  \[u3041] \[u3043] \[u3045] \[u3047] \[u3049] \[u3063] \[u3083] \[u3085] \
  \[u3087] \[u30FC] \
  \[u30A1] \[u30A3] \[u30A5] \[u30A7] \[u30A9] \[u30C3] \[u30E3] \[u30E5] \
  \[u30E7]
.class [CJKpostpunct] \
  \[uFF08] \[u3014] \[uFF3B] \[uFF5B] \[u300C] \[u300E] \[u3010]
.
.\"  Hiragana, Katakana, and Kanji glyphs.
.class [CJKnormal] \
  \[u3041]-\[u3096] \[u30A0]-\[u30FF] \[u4E00]-\[u9FFF]
.
.cflags 128 \C'[CJKprepunct]'
.cflags 266 \C'[CJKpostpunct]'
.cflags 512 \C'[CJKnormal]'
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~
.\" workaround: define some portability stuff
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq (aq
.el       .ds Aq
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~
.
.SH "NAME"
\fBwlt\fR \- login into ustc\-wlt service
.
.SH "SYNOPSIS"
\fBwlt\fR
.br
\fBwlt\fR \fB\-d\fR
.br
\fBwlt\fR \fB\-h\fR
.
.SH "DESCRIPTION"
\fBWlt\fR is a network service provided by USTC Networking and Information Center\. All students and teachers may own one wlt account to access Internet from within the campus using \fBustcnet\fR\. An attempt to log in on the wlt website \fBhttp://wlt\.ustc\.edu\.cn\fR is required\.
.
.P
\fBwlt(1)\fR is a shell script that can help wlt users to log in \fBwlt\.ustc\.edu\.cn\fR from command line easily\. By default, it is an interactive tool\. You simply need to type the login informations, then the script will finish the rest of the task\.
.
.P
Read the script code for more details\.
.
.SH "EXAMPLES"
Not provided now\. May be added soon\.
.
.SH "BUGS"
The program may misbehave in corner conditions\. So use it at your own risk\.
.
.SH "COPYRIGHT"
Copyright (C) 2015 Boyuan Yang \fIhosiet@mail\.ustc\.edu\.cn\fR
.
.SH "SEE ALSO"
curl(1), wget(1)
.
.P
http://wlt\.ustc\.edu\.cn/
